/* Generated By:JavaCC: Do not edit this line. MphFormatParserConstants.java */
package synalp.generation.morphology.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MphFormatParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<ID>",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"=\"",
    "\":\"",
    "\"|\"",
  };

}
