language: java
env:
  global:
  - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2048m -Xms1024m"
jdk:
- oraclejdk8
sudo: false
script:
- mvn clean package -e
- chmod a+x prepare-deploy-local-dir.sh
- "./prepare-deploy-local-dir.sh $TRAVIS_BUILD_DIR/nightly"
after_script:
- chmod a+x travis-promote.sh
- "./travis-promote.sh"
deploy:
- provider: s3
  access_key_id: AKIAJFIXOUR3SFD7OGMA
  secret_access_key:
  secure: Oy1JQ+GIui8dAZ1paLeGnzkahklWV3ADTVni0JuvSP25/jsZsS0LAGO0t8zfJtiD9vtUu3zaZmNEayJaFRhBauBHrPCmx06XVfcyYzSEKK1Rant7XkwQ1aX1b1Dd8vNs5abWN4OMc9OfMGuk0ilILAVgTYPhIXfGVXdsmwD3Qqn/iKDZ7VvdDN3wT/gBFsUkDNp+zgPA5A68qkt9ffGel2pXlAAaw1WNdsTRpY36ONLco+l8H/CaVTfcSNEH3PSpQdQ66EQtssGQ2nJ/skKUJ2rMgE3/XXvZvwlh6j2FEI9qw7D5ZVjWYDE7YshkNfz67xLk2kBmjVxvW0EtO1R2fqg51x5xW7jKWOXNEz8YZ/ra8alJfpamze5fdYL7Qegf5lxfTqdvEfFR0/zKOJ3VHCpF3HX+hxN70DU+t5t3BTZFVY0/0WKozHBxFnCl4187hMUKAWn1oP3QOvDQmiz3TGSw8me2J7xu/t3OOcK9Y//fj15l+hu7jViZnQxUzJ49lvXHqT2/oNjLS+78qyXtk+MEN0q+hwpMiCIZ7cwoRgJVnZdkV1jKYVE7NvV7ZX+AgkpgdR9vtz3Lli0Ayl/oYDPWX1nS1CTkXUEAGJ17e+Y5RXEfj598kpCGRvNknt9T4ofD/szYs8DFNTEiwhsmLhs0JK3mR/OyQKMIhJhyEpo=
  bucket: obeo-networkaggregation-releases
  local-dir: "${TRAVIS_BUILD_DIR}/nightly"
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  upload-dir: ModelWriter/${TRAVIS_BRANCH}
  on:
    all_branches: true
    repo: ModelWriter/Source
