language: java
env:
  global:
  - DISPLAY=:99.0
  - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2048m -Xms1024m"
  matrix:
  - PROFILE=platform-kepler
  - PROFILE=platform-luna
  - PROFILE=platform-mars
  - PROFILE=platform-neon,product,updatesites
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - $HOME/.m2
addons:
  apt:
    packages:
    - metacity
install: true
before_script:
- export SWT_GTK3=0
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1440x900x16
- sh -e /etc/init.d/xvfb start
- sleep 10
- metacity --sm-disable --replace &
- sleep 10
script:
- mvn clean package -e -P$PROFILE
- chmod a+x prepare-deploy-local-dir.sh
- if [[ $PROFILE == *"updatesites"* ]]; then ./prepare-deploy-local-dir.sh $TRAVIS_BUILD_DIR/nightly; export UPDATE_SITES=true; fi
- if [[ "$TRAVIS_TAG" != "" ]] && [[ "$PROFILE" == *"updatesites"* ]]; then ./prepare-deploy-local-dir.sh $TRAVIS_BUILD_DIR/$TRAVIS_TAG; fi
after_script:
- if [[ "$PROFILE" == *"updatesites"* ]]; then chmod a+x travis-promote.sh; fi
- if [[ "$PROFILE" == *"updatesites"* ]]; then ./travis-promote.sh; fi
deploy:
###### Nightly ######
- provider: s3
  access_key_id: AKIAJFIXOUR3SFD7OGMA
  secret_access_key:
    secure: FcT7vbnyhjqiQHpl9wJKjZzjDzr7/NtgYmfeL0XoulTDfxjF+Xz4zUD0AyOv/QFUcUeqipi9Iz3kTAInO25svCWILd1lf6yGNZVdamXv6/ORskrmeRCkNGoQQ0AuvCxEwbv1OjoWQcAbtAYlh+t/riy5MlrxhpwjFbYRRLYM4MkguPPIXUgagLduQuvKb/4v0XLVy7k7xu5wr/CLCEVBSzWc3LDTEtSaFrX/yx33SLxiFgLf+kudP5wGll+ZlbPoWWHCTm4c1hEm0/qfGnuXjjVYQu8yNyvp9bBE72OZCGU7dfxRI/ZkMVMXtZg4PP7bbdCa756nYbhBi8GC4yFdTeIkKA5XVMkMO0GJLbHAx2Y0hlyGMUdQnYlA3vDjKDquZy1ABVRHUUzK/Zgfs1aD5gW6pjzqnGUFM844ZQ45n4yYEidZSNu3+hyIxIY/wbDyTLH1PkciC8snsv4gb6u3ylzILITKL+vtPuI71ZEMKVco5T6MGcwcLPdvyUD+cAKeV6fBW8YDSR733W+3JrvbarxuLPyeIxolTI3yEKzjoTN2LK3R2YEEDulHAqyNy6Q9+JrYodjv9crobbaShg7yZRlHv+IIqh6Xu7X5yR8cu6d297uGo8fXI0dNLLnK9Ksj/JE02964x9IlAqfp4A4WmSJKJyZKFiBA1Hu7PDvhtAo=
  bucket: modelwriter-nightly
  local-dir: "${TRAVIS_BUILD_DIR}/nightly"
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  upload-dir: ${TRAVIS_BRANCH}
  on:
    branch: master
    repo: ModelWriter/Source
    condition: $UPDATE_SITES = true
###### Release ######
- provider: s3
  access_key_id: AKIAJFIXOUR3SFD7OGMA
  secret_access_key:
    secure: FcT7vbnyhjqiQHpl9wJKjZzjDzr7/NtgYmfeL0XoulTDfxjF+Xz4zUD0AyOv/QFUcUeqipi9Iz3kTAInO25svCWILd1lf6yGNZVdamXv6/ORskrmeRCkNGoQQ0AuvCxEwbv1OjoWQcAbtAYlh+t/riy5MlrxhpwjFbYRRLYM4MkguPPIXUgagLduQuvKb/4v0XLVy7k7xu5wr/CLCEVBSzWc3LDTEtSaFrX/yx33SLxiFgLf+kudP5wGll+ZlbPoWWHCTm4c1hEm0/qfGnuXjjVYQu8yNyvp9bBE72OZCGU7dfxRI/ZkMVMXtZg4PP7bbdCa756nYbhBi8GC4yFdTeIkKA5XVMkMO0GJLbHAx2Y0hlyGMUdQnYlA3vDjKDquZy1ABVRHUUzK/Zgfs1aD5gW6pjzqnGUFM844ZQ45n4yYEidZSNu3+hyIxIY/wbDyTLH1PkciC8snsv4gb6u3ylzILITKL+vtPuI71ZEMKVco5T6MGcwcLPdvyUD+cAKeV6fBW8YDSR733W+3JrvbarxuLPyeIxolTI3yEKzjoTN2LK3R2YEEDulHAqyNy6Q9+JrYodjv9crobbaShg7yZRlHv+IIqh6Xu7X5yR8cu6d297uGo8fXI0dNLLnK9Ksj/JE02964x9IlAqfp4A4WmSJKJyZKFiBA1Hu7PDvhtAo=
  bucket: modelwriter-releases
  local-dir: "${TRAVIS_BUILD_DIR}/${TRAVIS_TAG}"
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  upload-dir: ${TRAVIS_TAG}
  on:
    tags: true
    all_branches: true
    repo: ModelWriter/Source
    condition: $UPDATE_SITES = true

