<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ide" nsURI="http://www.modelwriter.eu/mapping/ide" nsPrefix="ide">
  <eClassifiers xsi:type="ecore:EClass" name="ResourceLocation" eSuperTypes="../../org.eclipse.mylyn.docs.intent.mapping.emf/model/mapping.ecore#//Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileLocation" eSuperTypes="#//ResourceLocation"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextFileLocation" eSuperTypes="#//FileLocation ../../org.eclipse.mylyn.docs.intent.mapping.emf/model/mapping.ecore#//TextContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectFileLocation" eSuperTypes="#//FileLocation ../../org.eclipse.mylyn.docs.intent.mapping.emf/model/mapping.ecore#//EObjectContainer"/>
</ecore:EPackage>
