/* Generated By:JavaCC: Do not edit this line. InputReaderConstants.java */
package synalp.commons.input.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface InputReaderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int DOT = 7;
  /** RegularExpression Id. */
  int FSTYPE = 8;
  /** RegularExpression Id. */
  int ID = 9;
  /** RegularExpression Id. */
  int TEXT = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\",\"",
    "\".\"",
    "<FSTYPE>",
    "<ID>",
    "<TEXT>",
    "\"@start\"",
    "\"@ignore\"",
    "\"@first\"",
    "\"@only\"",
    "\"@morph\"",
    "\"@stop\"",
    "\"@strict\"",
    "\"@loose\"",
    "\"semantics:[\"",
    "\"]\"",
    "\"sentence:\"",
    "\"~\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"?\"",
    "\"|\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"=\"",
  };

}
