/* Generated By:JavaCC: Do not edit this line. LexFormatParserConstants.java */
package synalp.commons.lexicon.lexformat.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexFormatParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MACROPATH = 6;
  /** RegularExpression Id. */
  int ID = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<MACROPATH>",
    "<ID>",
    "\"include \"",
    "\"*ENTRY:\"",
    "\"*CAT:\"",
    "\"*SEM:\"",
    "\"*ACC:\"",
    "\"*FAM:\"",
    "\"*FILTERS:\"",
    "\"*EX:\"",
    "\"{\"",
    "\"}\"",
    "\"*EQUATIONS:\"",
    "\"*COANCHORS:\"",
    "\"->\"",
    "\"/\"",
    "\"semantics:\"",
    "\"[\"",
    "\"]\"",
    "\"interface:\"",
    "\",\"",
    "\"=\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"?\"",
  };

}
