/* Generated By:JavaCC: Do not edit this line. PatternReaderConstants.java */
package synalp.generation.jeni.selection.patterns.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PatternReaderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int DOT = 7;
  /** RegularExpression Id. */
  int FSTYPE = 8;
  /** RegularExpression Id. */
  int FOR = 9;
  /** RegularExpression Id. */
  int ASSUME = 10;
  /** RegularExpression Id. */
  int SELECT = 11;
  /** RegularExpression Id. */
  int COSELECT = 12;
  /** RegularExpression Id. */
  int WHEN = 13;
  /** RegularExpression Id. */
  int WITH = 14;
  /** RegularExpression Id. */
  int SET = 15;
  /** RegularExpression Id. */
  int EXCLUDE = 16;
  /** RegularExpression Id. */
  int SHALLOW = 17;
  /** RegularExpression Id. */
  int OPTIONAL = 18;
  /** RegularExpression Id. */
  int REWRITE = 19;
  /** RegularExpression Id. */
  int BY = 20;
  /** RegularExpression Id. */
  int COANCHOR = 21;
  /** RegularExpression Id. */
  int ID = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\",\"",
    "\".\"",
    "<FSTYPE>",
    "\"for\"",
    "\"assume\"",
    "\"select\"",
    "\"coselect\"",
    "\"when\"",
    "\"with\"",
    "\"set\"",
    "\"exclude\"",
    "\"shallow\"",
    "\"optional\"",
    "\"rewrite\"",
    "\"by\"",
    "\"coanchor\"",
    "<ID>",
    "\":\"",
    "\"\\\"\"",
    "\"=\"",
    "\"?\"",
    "\"|\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
  };

}
